"""added userevent roles

Revision ID: 6942c46563ff
Revises: 945e2212e86f
Create Date: 2025-01-28 15:08:33.827836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6942c46563ff'
down_revision = '945e2212e86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
