"""fixed event to include location

Revision ID: 945e2212e86f
Revises: 24ae25fad83f
Create Date: 2025-01-27 12:05:01.377372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945e2212e86f'
down_revision = '24ae25fad83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
